### ISSUE TITLE
Memory setting does not work

### ISSUE THREAD

**Issue by nkwangjun** [futurewei-cloud/arktos-vm-runtime#27]
vm definition yaml as follows:
```
apiVersion: v1
kind: Pod
metadata:
  name: testcirros
  annotations:
    kubernetes.io/target-runtime: virtlet.cloud
spec:
  virtualMachine:
    name: testcirros
    image: localhost/cirros-0.3.5-x86_64-disk.img
    imagePullPolicy: IfNotPresent
    publicKey: nokey
    resources:
      limits:
        cpu: "2"
        memory: "900Mi"
      requests:
        cpu: "2"
        memory: "900Mi"
```

The memory does not work:
```
root@arktos:~/work/yaml# kubectl describe pods testcirros
Name:         testcirros
Namespace:    default
Tenant:       system
Priority:     0
Node:         arktos/192.168.10.239
Start Time:   Mon, 25 May 2020 09:15:40 +0000
Labels:       <none>
Annotations:  kubernetes.io/target-runtime: virtlet.cloud
Status:       Running
IP:           10.88.0.76
Containers: <none>
Conditions:
  Type           Status
  Ready          True
  PodScheduled   True
Volumes:         <none>
QoS Class:       Guaranteed
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
root@arktos:~/work/yaml# vcrictl pods --name testcirros
POD ID              CREATED             STATE               NAME                NAMESPACE           ATTEMPT
5655d3c9-b03f       2 hours ago         Ready               testcirros          default             0
root@arktos:~/work/yaml# vcrictl ps
CONTAINER           IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID
404ea87e-8ff6       e137062a4dfbb       2 hours ago         Running             testcirros          0                   5655d3c9-b03f
b99e39ee-4da3       e137062a4dfbb       4 hours ago         Running             vmcirrosdep         0                   3b916578-aa99
root@arktos:~/work/yaml# virtletctl virsh list
*** node: arktos pod: virtlet-xdt76 ***
 Id    Name                           State
----------------------------------------------------
 2     virtlet-b99e39ee-4da3-vmcirrosdep running
 7     virtlet-404ea87e-8ff6-testcirros running


root@arktos:~/work/yaml# virtletctl virsh dumpxml 7
*** node: arktos pod: virtlet-xdt76 ***
<domain type='qemu' id='7' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>
  <name>virtlet-404ea87e-8ff6-testcirros</name>
  <uuid>404ea87e-8ff6-5e48-5dd6-b8e63f840d84</uuid>
  <memory unit='KiB'>1048576</memory>
  <currentMemory unit='KiB'>1048576</currentMemory>
  <vcpu placement='static'>2</vcpu>
  <cputune>
    <shares>2</shares>
    <period>100000</period>
```

**Comment by yb01** [comment]
Thanks for reporting the issue. This is a bug in the podConverter in Arktos code base. will fix the bug there.

**Comment by nkwangjun** [comment]
it works! thanks~~

```
root@arktos:~/work/src/github.com/arktos# cat ../../../yaml/cirros.yaml
apiVersion: v1
kind: Pod
metadata:
  name: testcirros
  annotations:
    kubernetes.io/target-runtime: virtlet.cloud
spec:
  virtualMachine:
    name: testcirros
    image: localhost/cirros-0.3.5-x86_64-disk.img
    imagePullPolicy: IfNotPresent
    publicKey: nokey
    resources:
      limits:
        cpu: "2"
        memory: "900Mi"
      requests:
        cpu: "2"
        memory: "900Mi"
root@arktos:~/work/src/github.com/arktos# virtletctl virsh dumpxml virtlet-20f688f7-0a9b-testcirros
*** node: arktos pod: virtlet-gfxpq ***
<domain type='qemu' id='1' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>
  <name>virtlet-20f688f7-0a9b-testcirros</name>
  <uuid>20f688f7-0a9b-560e-6a59-dbb653ac92b5</uuid>
  <memory unit='KiB'>921600</memory>
  <currentMemory unit='KiB'>921600</currentMemory>
```
